### ISSUE TITLE
feature request: actual user-ranking within the current month

### ISSUE THREAD

**Issue by bug-i** [3D-I/tpotm#19]
I would find an overview with the status of the current month helpful. Right now you can just guess who is second and third, and how much post they are behind the current tpotm.

Maybe an extra site that list the first 5 (or 10) users with their actual monthly posting can solve this.
As I have seen that you intend to create an extra site with an overview of all previus tpotm - you can implement this information there too. (Just for the current month, no history required)

**Comment by 3D-I** [comment]
Thanks for feedback, I will see.

**Comment by 3D-I** [comment]
Your request doesn't fit into to the purpose of this extension.
Thanks for feedback.
