### ISSUE TITLE
Cant Change language, if tpotm activated

### ISSUE THREAD

**Issue by neckflo** [3D-I/tpotm#64]
If i want to change the Userlanguage in my profile, this error is showing: 
I tryed british and american english. 

Server-Typ: MySQL
Server-Version: 5.7.20 - MySQL
PHP-Version: | 7.1.11-1+0~
Version des Boards: | 3.2.1

SQL ERROR [ mysqli ]

Unknown column 'user_tt_tpotm' in 'field list' [1054]

SQL

UPDATE databasename2017_users SET user_allow_pm = 1, user_allow_viewemail = 1, user_allow_massemail = 1, user_allow_viewonline = 1, user_notify_type = '0', user_options = '231295', user_dateformat = 'j. M Y, H:i', user_lang = 'en_us', user_timezone = 'Europe/Berlin', user_style = 1, user_scl_enabled = 1, user_snow_enabled = 1, user_elonw = 1, user_tt_tpotm = 0, user_tt_sel_tpotm = 0 WHERE user_id = 2

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/includes/ucp/ucp_prefs.php
LINE: 129
CALL: phpbb\db\driver\factory->sql_query()

FILE: [ROOT]/includes/functions_module.php
LINE: 676
CALL: ucp_prefs->main()

FILE: [ROOT]/ucp.php
LINE: 394
CALL: p_master->load_active()

**Comment by 3D-I** [comment]
Wich TPOTM version are you using?

**Comment by neckflo** [comment]
Sorry forgot the version: 2.0.5-RC

**Comment by 3D-I** [comment]
phpBB version? 

have you copied/translated the EN folder of the TPOTM ext/language to the new language with the correct iso-code?

**Comment by 3D-I** [comment]
To me it looks like you upgraded to the version 2.0.5-rc without deleting data.

Do this: disable/**delete data**/ and .. enable again the extension.

Pls report, thank you!

**Comment by neckflo** [comment]
Thank you very much. This work for me "Do this: disable/delete data/ and .. enable again the extension."
Issue can be closed. Thank you for your help and great extension!
