### ISSUE TITLE
Pagination Bug

### ISSUE THREAD

**Issue by DigitalFuturePT** [3D-I/tpotm#68]
**Describe the bug**
The Pagination Doesn't Work

**To Reproduce**
1. Go to tpotm/hall_of_fame page
2. Click on the arrow of pagination or any page number
3. Note that the url is now tpotm/tpotm/hall_of_fame?start=16

**Expected behavior**
The pagination should work and show the next userlist

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 75

**Additional context**
It happened on 2.0.9, and even with this latest 2.1.0

**Comment by 3D-I** [comment]
https://rhea.phpbbstudio.com/tpotm/hall_of_fame
